#!/bin/sh
# stash unstaged changes, run release task, stage release updates and restore stashed files
PATH=$PATH:/usr/local/bin:/usr/local/sbin
NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ "$NAME" != '(no branch)' ]
then
  npm run precommit
  git diff --name-only --cached | xargs git add
  STASH_OUTPUT=$(git stash --keep-index)
  npm test
  RETVAL=$?
  if [ "$STASH_OUTPUT" != "No local changes to save" ]
  then
    git stash pop -q
  fi
  if [ $RETVAL -ne 0 ]
  then
    exit 1
  fi
fi
